// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example for VibeKit template.
/// This will be replaced by the CLI configure tool with your actual Firebase project configuration.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'VIBEKIT_WEB_API_KEY',
    appId: 'VIBEKIT_WEB_APP_ID',
    messagingSenderId: 'VIBEKIT_MESSAGING_SENDER_ID',
    projectId: 'vibekit-template',
    authDomain: 'vibekit-template.firebaseapp.com',
    storageBucket: 'vibekit-template.appspot.com',
    measurementId: 'VIBEKIT_WEB_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'VIBEKIT_ANDROID_API_KEY',
    appId: 'VIBEKIT_ANDROID_APP_ID',
    messagingSenderId: 'VIBEKIT_MESSAGING_SENDER_ID',
    projectId: 'vibekit-template',
    storageBucket: 'vibekit-template.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'VIBEKIT_IOS_API_KEY',
    appId: 'VIBEKIT_IOS_APP_ID',
    messagingSenderId: 'VIBEKIT_MESSAGING_SENDER_ID',
    projectId: 'vibekit-template',
    storageBucket: 'vibekit-template.appspot.com',
    iosBundleId: 'com.vibekit.vibekit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'VIBEKIT_MACOS_API_KEY',
    appId: 'VIBEKIT_MACOS_APP_ID',
    messagingSenderId: 'VIBEKIT_MESSAGING_SENDER_ID',
    projectId: 'vibekit-template',
    storageBucket: 'vibekit-template.appspot.com',
    iosBundleId: 'com.vibekit.vibekit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'VIBEKIT_WINDOWS_API_KEY',
    appId: 'VIBEKIT_WINDOWS_APP_ID',
    messagingSenderId: 'VIBEKIT_MESSAGING_SENDER_ID',
    projectId: 'vibekit-template',
  );
}
